---
- name: Clone / update the repository
  git:
    repo: 'https://github.com/sc2pte/panel-backend.git'
    dest: '{{ sc2pte_deploy_directory }}'
    depth: 1
    force: yes
  register: sc2pte_git_clone

- name: Check if previous deployment exists
  stat:
    path: "{{ sc2pte_deploy_directory }}"
  register: sc2pte_previous_deployment
  when: force_deploy is defined and force_deploy == True or sc2pte_git_clone.changed

- name: Ensure backup directory exists
  file:
    path: "{{ sc2pte_backup_directory }}"
    state: directory
  when: force_deploy is defined and force_deploy == True or sc2pte_git_clone.changed

- name: Backup previous deployment
  archive:
    path: "{{ sc2pte_deploy_directory }}"
    dest: "{{ sc2pte_backup_directory }}/{{ lookup('pipe','date +%Y-%m-%d_%H-%M-%S') }}.tgz"
  changed_when: false
  when: force_deploy is defined and force_deploy == True or sc2pte_git_clone.changed and sc2pte_previous_deployment.stat.exists

- name: Stop running project instance in pm2
  command: 'pm2 stop {{ sc2pte_pm2_project_name }}'
  failed_when: false
  when: force_deploy is defined and force_deploy == True or sc2pte_git_clone.changed

- name: Set environment variables
  lineinfile:
    dest: /etc/environment
    regexp: "^{{ item.name }}="
    line: "{{ item.name }}={{ item.value }}"
    state: present
  with_items:
    - name: "NODE_ENV"
      value: "{{ NODE_ENV }}"
    - name: "SC2PTE_NODE_ENV"
      value: "{{ SC2PTE_NODE_ENV }}"
    - name: "SC2PTE_NODE_PORT"
      value: "{{ SC2PTE_NODE_PORT }}"
    - name: "SC2PTE_URL_PREFIX"
      value: "{{ SC2PTE_URL_PREFIX }}"
    - name: "SC2PTE_SAS_URL"
      value: "{{ SC2PTE_SAS_URL }}"
    - name: "SC2PTE_SAS_STATUS_ENDPOINT"
      value: "{{ SC2PTE_SAS_STATUS_ENDPOINT }}"
    - name: "SC2PTE_REDIS_ENABLE"
      value: "{{ SC2PTE_REDIS_ENABLE }}"
    - name: "SC2PTE_REDIS_HOST"
      value: "{{ SC2PTE_REDIS_HOST }}"
    - name: "SC2PTE_REDIS_PORT"
      value: "{{ SC2PTE_REDIS_PORT }}"
    - name: "SC2PTE_REDIS_PASSWORD"
      value: "{{ SC2PTE_REDIS_PASSWORD }}"
    - name: "SC2PTE_REDIS_DB"
      value: "{{ SC2PTE_REDIS_DB }}"
    - name: "SC2PTE_REDIS_CACHE_SEGMENT"
      value: "{{ SC2PTE_REDIS_CACHE_SEGMENT }}"
    - name: "SC2PTE_REDIS_TTL_SECS"
      value: "{{ SC2PTE_REDIS_TTL_SECS }}"
    - name: "SC2PTE_MONGODB_CONNECTION_STRING"
      value: "{{ SC2PTE_MONGODB_CONNECTION_STRING }}"
    - name: "SC2PTE_TWITCH_EXTENSION_CLIENT_SECRET"
      value: "{{ SC2PTE_TWITCH_EXTENSION_CLIENT_SECRET }}"
    - name: "SC2PTE_CLOUDFLARE_ENABLE"
      value: "{{ SC2PTE_CLOUDFLARE_ENABLE }}"
    - name: "SC2PTE_CLOUDFLARE_API_TOKEN"
      value: "{{ SC2PTE_CLOUDFLARE_API_TOKEN }}"
    - name: "SC2PTE_CLOUDFLARE_ZONE_ID"
      value: "{{ SC2PTE_CLOUDFLARE_ZONE_ID }}"
    - name: "SC2PTE_CLOUDFLARE_PRODUCTION_DOMAIN"
      value: "{{ SC2PTE_CLOUDFLARE_PRODUCTION_DOMAIN }}"
    - name: "SC2PTE_ENABLE_TWITCH_EXT_ONAUTHORIZED"
      value: "{{ SC2PTE_ENABLE_TWITCH_EXT_ONAUTHORIZED }}"
    - name: "SC2PTE_MAXIMUM_PROFILE_COUNT"
      value: "{{ SC2PTE_MAXIMUM_PROFILE_COUNT }}"
  become: true
  when: force_deploy is defined and force_deploy == True or sc2pte_git_clone.changed

- name: Remove node_modules directory
  file:
    path: '{{ sc2pte_deploy_directory }}/node_modules'
    state: absent
  when: force_deploy is defined and force_deploy == True or sc2pte_git_clone.changed

- name: Install packages
  npm:
    path: '{{ sc2pte_deploy_directory }}'
  when: force_deploy is defined and force_deploy == True or sc2pte_git_clone.changed

- name: Build project
  command: 'npm run build --prefix {{ sc2pte_deploy_directory }}'
  when: force_deploy is defined and force_deploy == True or sc2pte_git_clone.changed

- name: Delete running project instance from pm2
  command: 'pm2 delete {{ sc2pte_pm2_project_name }}'
  failed_when: false
  when: force_deploy is defined and force_deploy == True or sc2pte_git_clone.changed

- name: Start project in pm2
  command: 'pm2 start {{ sc2pte_deploy_directory }}/scripts/start.js -i max --name {{ sc2pte_pm2_project_name }} --watch --update-env -f'
  when: force_deploy is defined and force_deploy == True or sc2pte_git_clone.changed

- name: Setup configuration as startup script
  command: 'env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u lwoo --hp /home/lwoo'
  become: true
  when: force_deploy is defined and force_deploy == True or sc2pte_git_clone.changed
